### ISSUE TITLE
Setting the browser language

### ISSUE THREAD

**Issue by acailly** [cognitom/wdio-phantomjs-service#1]
How can we set the browser language when using this service?

I tried setting theses capabilities but nothing works:

```
    capabilities: [{
        browserName: 'phantomjs',
        'intl.accept_languages': 'en-us',
        'phantomjs.page.customHeaders.Accept-Language':'en-us',
        'phantomjs.customHeaders.Accept-Language':'en-us',
        'Accept-Language':'en-us'        
    }],
```

Using:
- webdriverio@4.2.7
- wdio-phantomjs-service@0.1.0

**Comment by cognitom** [comment]
@acailly this service just launches PhantomJS. The support of `capability` is up to [ghostdriver](https://github.com/detro/ghostdriver) which is the part of PhantomJS. Good luck.
