### ISSUE TITLE
how it works?

### ISSUE THREAD

**Issue by GGuru** [cognitom/wdio-phantomjs-service#5]
Can you help me understand how this works?

How is this different from using wdio-selenium-standalone-service and specifying phantomjs in the capabilities? From a cursory look, I don't think this uses wdio-selenium-standalone. how does it invoke phantomjs without selenium server?

**Comment by cognitom** [comment]
Hi @GGuru,

Selenium Server is a kind of "hub". We could easily access multiple browsers through it. But if we use only PhantomJS, we don't need to use that "hub". We can connect to PhantomJS via WebDriver directly.

What `wdio-phantomjs-service` does is just two:
- installs `phantomjs-prebuilt` as a dependency
- runs PhantomJS during the test with `wdio`

I hope it would be an answer for your question.

**Comment by GGuru** [comment]
Thanks @cognitom That helps.
